server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/info_streamingmusica
    username: root
    password: 'Triclion01!'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
